### ISSUE TITLE
METAR change

### ISSUE THREAD

**Issue by marostegui** [auria/epabot#4]
Hello, 

PyMETAR uses http://weather.noaa.gov/pub/data/observations/metar/decoded/ which is no longer available

This is still available though:

curl "https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&stationString=LEMD&hoursBeforeNow=1" | grep -m1 raw_text

And retrieves: <raw_text>LEMD 241700Z 13009KT CAVOK 35/01 Q1017 NOSIG</raw_text>

You can also use: &hoursBeforeNow=1
If you want all the METARs in the last X hours.

**Comment by auria** [comment]
Thank you Manuel. We will contact pyMETAR developer, too.

**Comment by victorcete** [comment]
+1 can we get this working?

**Comment by auria** [comment]
https://github.com/auria/epabot/commit/d1defdee150c2750d177b357d0fd539140705344

**Comment by marostegui** [comment]
I can confirm this works.
Thanks for solving this issue so fast. Much appreciated.
